import ReactQueryProviders from "@/hooks/useReactQuery";
import StyledComponentsRegistry from "@/lib/registry";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import "rc-calendar/assets/index.css";
import Provider from "./Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProviders>
          <StyledComponentsRegistry>
            <Provider>{children}</Provider>
          </StyledComponentsRegistry>
        </ReactQueryProviders>
      </body>
    </html>
  );
}
